Optionally skip create table with optional flag
node-casbin/sequelize-adapter pull request #71
Opened 2023-01-31 15:50 UTC by rogersgt

See my question int he issues section of the `node-casbin` repo: https://github.com/casbin/node-casbin/issues/418. If there is already a way to do this, or a better pattern, I'm all for it. But I really think this is needed for many enterprise implementations.

2023-02-01 14:35 UTC, hsluoyz requested changes

2023-02-01 14:35 UTC, hsluoyz commented on src/adapter.ts
> +  constructor(option: SequelizeAdapterOptions, autoCreate = true) {
autoCreateTable

2023-02-01 14:35 UTC, hsluoyz commented on src/adapter.ts
>    public static async newAdapter(
Add the new usage to README.md

https://github.com/node-casbin/sequelize-adapter#simple-example

2023-02-03 13:41 UTC, hsluoyz commented
@rogersgt

2023-02-14 23:42 UTC, hsluoyz commented
@rogersgt hi, can you fix the issues according to the review?

2023-02-18 01:01 UTC, hsluoyz commented
Replaced by: https://github.com/node-casbin/sequelize-adapter/pull/73

2023-02-18 01:01 UTC, closed without merging

2023-02-22 23:24 UTC, rogersgt commented
Sorry for the delay here. Thanks for making the change @terry-xuan-gao!